# Generated by Django 2.0.2 on 2018-10-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(' ', ' '), ('m', 'Male'), ('f', 'Female')], default=' ', max_length=10),
        ),
    ]
