# Generated by Django 2.0.2 on 2018-10-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181021_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[(' ', ' '), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
