# Generated by Django 2.0.2 on 2018-10-25 10:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/goods/'),
        ),
    ]
