# Generated by Django 2.0.2 on 2018-10-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pub_date',)},
        ),
    ]
